// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hreljckpbskhkfsvrhbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyZWxqY2twYnNraGtmc3ZyaGJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTc5NDYsImV4cCI6MjA2NzYzMzk0Nn0.HyFzcmH52kxyTeXdaeQKY9S9k0gpixid6ekAS_c2Ifo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});